### PR TITLE
6 m's are better than 5 m's

### PR DESCRIPTION
**Pull request by ItzCraft**
yes. >w<

### CODE REVIEW

**Comment by alnyled** [comment]
wtf is this

no

**Comment by ItzCraft** [comment]
plese

**Comment by alnyled** [comment]
why :hognar:

**Comment by ItzCraft** [comment]
why not tho?

**Comment by alnyled** [comment]
i will consume your soul

**Comment by ItzCraft** [comment]
Sure

**Comment by alnyled** [comment]
this is very based

**Comment by ItzCraft** [comment]
:cry:

**Comment by ItzCraft** [comment]
WHAT

**Comment by ItzCraft** [comment]
HOW ITS WORKED

**Comment by AnDashikKozlov** [comment]
what the fuck is gonig on here?

**Comment by alnyled** [comment]
wait wht

**Comment by alnyled** [comment]
impossible

**Comment by N4H4N** [comment]
wth is this?

**Comment by alnyled** [comment]
> wth is this?

no clue

**Comment by alnyled** [comment]
ask itz not me

**Pull request closed without merging**
